#Pais
#Estados Total
estados=[centroOeste,Norte,Nordeste,sul,Sudeste]
CasosAcumulado=[[48232]]
centroOeste=["Distrito Federal","Goiás","Mato Grosso","Mato Grosso do Sul"]
Norte=["Acre ","Amapá","Amazonas","Rondônia","Roraima","Tocantins","Pará"]
Noedeste=["Alagoas ","Bahia","Ceará ","Maranhão","Paraíba","Pernambuco","Piauí","Rio Grande do Norte","Sergipe"]
sul=["Rio Grande do Sul","Santa Catarina","Paraná"]
Sudeste=["Rio de Janeiro","São Paulo ","Espírito Santo","Minas Gerais"]
MunicipiosNO=[["Alta Floresta D OESTE"]]
RegioesNO=[["Zona da mata"]]
PopulacaoNO=[[22945]]
CasosAcumuladoNO=[[415]]
ObitosAcumuladosNO=[[4]]
CasosNovosNO=[[6]]
ObitosNovosNO=[[0]]
