# Atividade contextualizada 3

print('<<<<Microscópio Confocal de varredura à laser>>> ')
print('')
print('Esse programa tem como objetivo receber dados para serem utilizados pelo equipamento para realizar a captura das imagens. Por favor, insira os seguintes dados:')
print('')
tipodeCelulain = 5 #variar de 1 a 10 
zoomin = 500 #Variar de 50 a 5000
resolucaoin = 1000 #variar de 1000 a 5000
aberturaFocoin= 1.5 #variar de 0.1 a 2 
faixadeiluminacaoin = 6 #variar de 1 a 15
contrastein = 50 #varirar de  0 a 100 
brilhoin = 70 #variar de 0 a 100 
eixoXin= 150 #(0 e 500)
eixoYin= 250 #(0 e 500)
eixoZin= 350 #(0 e 500)
tipodeCelula = int(input('Digite o tipo de célula a ser encontrada (1 a 10): '))
print('Houve alteração de variável inserida? ', tipodeCelula != tipodeCelulain)
print('')
zoom = int(input('Digite o zoom da imagem (Entre 100 e 5000): '))
print('Houve alteração da variável inserida? ', zoom != zoomin)
print('')
resolucao = float(input('Digite a resolução da imagem (Entre 1000 e 5000): '))
print('Houve alteração da variável inserida? ', resolucao != resolucaoin)
print('')
aberturadeFoco = float(input('Digite a abertura do foco (Entre 0.1 e 2): '))
print('Houve alteração da variável inserida? ', aberturadeFoco != aberturaFocoin)
print('')
faixadeiluminacao = int(input('Digite a faixa de iluminação (Entre 1 e 15): '))
print('Houve alteração da variável inserida? ', faixadeiluminacao != faixadeiluminacaoin)
print('')
contraste = int(input('Digite o contraste (Entre 0 e 100): '))
print('Houve alteração da variável inserida? ', contraste != contrastein)
print('')
brilho = int(input('Digite o brilho (Entre 0 e 100):'))
print('Houve alteração da variável inserida? ', brilho != brilhoin)
print('')
eixoX = int(input('Digite a posição X (Entre 0 e 500): '))
print('Houve alteração da variável inserida? ', eixoX != eixoXin)
print('')
eixoY = int(input('Digite a posição Y (Entre 0 e 500): '))
print('Houve alteração da variável inserida? ', eixoY != eixoYin)
print('')
eixoZ = int(input('Digite a posição Z (Entre 0 e 500): '))
print('Houve alteração da variável inserida? ', eixoZ != eixoZin)
print('')
print('Definições:')
print('')
print('Tipo de célula: %s' %(tipodeCelula))
print('')
print('Zoom: %s' %(zoom))
print('')
print('Resolução: %s' %(resolucao))
print('')
print('Abertura de Foco: %s' %(aberturadeFoco))
print('')
print('Faixa de iluminação: %s' %(faixadeiluminacao))
print('')
print('Contraste: %s' %(contraste))
print('')
print('Brilho: %s' %(brilho))
print('')
print('Eixo X: %s' %(eixoX))
print('')
print('Eixo Y: %s' %(eixoY))
print('')
print('Eixo Z: %s' %(eixoZ))
print('')

#Calibração com a primeira letra
print('Para calibrarmos o eixo horizontal, por favor, digite a primeira letra do seu nome enquanto solicitado')
print('')
primeiraletra = str(input("Digite a primeira letra do seu nome: "))
print('Letra: %s' %(primeiraletra))
print('')
primeiraletra1 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(primeiraletra1))
print('Igual as anteriores: ', primeiraletra1 == primeiraletra)
print('')
primeiraletra2 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(primeiraletra2))
print('Igual as anteriores: ', primeiraletra2 == primeiraletra)
print('')
primeiraletra3 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(primeiraletra3))
print('Igual as anteriores: ', primeiraletra3 == primeiraletra)
print('')
primeiraletra4 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(primeiraletra4))
print('Igual as anteriores: ', primeiraletra4 == primeiraletra)
print('')
primeiraletra5 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(primeiraletra5))
print('Igual as anteriores: ', primeiraletra5 == primeiraletra)
print('')
primeiraletra6 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(primeiraletra6))
print('Igual as anteriores: ', primeiraletra6 == primeiraletra)
print('')
primeiraletra7 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(primeiraletra7))
print('Igual as anteriores: ', primeiraletra7 == primeiraletra)
print('')
primeiraletra8 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(primeiraletra8))
print('Igual as anteriores: ', primeiraletra8 == primeiraletra)
print('')
primeiraletra9 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(primeiraletra9))
print('Igual as anteriores: ', primeiraletra9 == primeiraletra)
print('')

#Última letra
print('Por favor, digite a última letra do seu nome enquanto solicitado')
print('')
ultimaletra = str(input("Digite a primeira letra do seu nome: "))
print('Letra: %s' %(ultimaletra))
print('')
ultimaletra1 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(ultimaletra1))
print('Igual as anteriores: ', ultimaletra1 == ultimaletra)
print('')
ultimaletra2 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(ultimaletra2))
print('Igual as anteriores: ', ultimaletra2 == ultimaletra)
print('')
ultimaletra3 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(ultimaletra3))
print('Igual as anteriores: ', ultimaletra3 == ultimaletra)
print('')
ultimaletra4 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(ultimaletra4))
print('Igual as anteriores: ', ultimaletra4 == ultimaletra)
print('')
ultimaletra5 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(ultimaletra5))
print('Igual as anteriores: ', ultimaletra5 == ultimaletra5)
print('')
ultimaletra6 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(ultimaletra6))
print('Igual as anteriores: ', ultimaletra6 == ultimaletra)
print('')
ultimaletra7 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(ultimaletra7))
print('Igual as anteriores: ', ultimaletra7 == ultimaletra)
print('')
ultimaletra8 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(ultimaletra8))
print('Igual as anteriores: ', ultimaletra8 == ultimaletra)
print('')
ultimaletra9 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(ultimaletra9))
print('Igual as anteriores: ', ultimaletra9 == ultimaletra)
print('')

#Calibrar eixo vertical
print('Para calibrarmos o eixo vertical, por favor, digite a segunda letra do seu nome enquanto solicitado')
print('')
segundaletra = str(input("Digite a primeira letra do seu nome: "))
print('Letra: %s' %(segundaletra))
print('')
segundaletra1 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(segundaletra))
print('Igual as anteriores: ', segundaletra1 == segundaletra)
print('')
segundaletra2 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(segundaletra2))
print('Igual as anteriores: ', segundaletra2 == segundaletra)
print('')
segundaletra3 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(segundaletra3))
print('Igual as anteriores: ', segundaletra3 == segundaletra)
print('')
segundaletra4 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(segundaletra4))
print('Igual as anteriores: ', segundaletra4 == segundaletra)
print('')
segundaletra5 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(segundaletra5))
print('Igual as anteriores: ', segundaletra5 == segundaletra)
print('')
segundaletra6 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(segundaletra6))
print('Igual as anteriores: ', segundaletra6 == segundaletra)
print('')
segundaletra7 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(segundaletra7))
print('Igual as anteriores: ', segundaletra7 == segundaletra)
print('')
segundaletra8 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(segundaletra8))
print('Igual as anteriores: ', segundaletra8 == segundaletra)
print('')
segundaletra9 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(segundaletra9))
print('Igual as anteriores: ', segundaletra9 == segundaletra)
print('')

#Penúltima letra
print('Por favor, digite a penúltima letra do seu nome enquanto solicitado')
print('')
penultimaletra = str(input("Digite a primeira letra do seu nome: "))
print('Letra: %s' %(penultimaletra))
print('')
penultimaletra1 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(penultimaletra1))
print('Igual as anteriores: ', penultimaletra1 == penultimaletra)
print('')
penultimaletra2 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(penultimaletra2))
print('Igual as anteriores: ', penultimaletra2 == penultimaletra)
print('')
penultimaletra3 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(penultimaletra3))
print('Igual as anteriores: ', penultimaletra3 == penultimaletra)
print('')
penultimaletra4 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(penultimaletra4))
print('Igual as anteriores: ', penultimaletra4 == penultimaletra)
print('')
penultimaletra5 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(penultimaletra5))
print('Igual as anteriores: ', penultimaletra5 == penultimaletra)
print('')
penultimaletra6 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(penultimaletra6))
print('Igual as anteriores: ', penultimaletra6 == penultimaletra)
print('')
penultimaletra7 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(penultimaletra7))
print('Igual as anteriores: ', penultimaletra7 == penultimaletra)
print('')
penultimaletra8 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(penultimaletra8))
print('Igual as anteriores: ', penultimaletra8 == penultimaletra)
print('')
penultimaletra9 = str(input('Digite a primeira letra do seu nome:' ))
print('Letra: %s' %(penultimaletra9))
print('Igual as anteriores: ', penultimaletra9 == penultimaletra)
print('')
print('A calibração está completa!')