# Aula 03 - Exercício 01 - índice de massa corporal (IMC)
# Realizada a atulização de entrada de dados (Exercício 2)

print('Índice de Massa Corpotal (IMC)')
altura = float(input('Por favor, digite a sua altura:'))
peso = float(input('Por favor, digite o seu peso:'))
print('Sua altura é %sm e o seu peso é %skg' %(altura, peso))
imc = peso/(altura**2)
print('Seu IMC é: %s' %(imc))
print('')
print('Muito abaixo do peso:', imc < 17)
print('')
print('Abaixo do peso normal:', 17 <= imc <18.5)
print('')
print('Dentro do peso normal:', 18.5 <= imc <25)
print('')
print('Acima do peso normal:', 25<=imc<30)
print('')
print('Muito acima do peso:', imc>30)
