#declaraçao de variaveis 
objetiva = 10
laser = 488
pinhole = "aberto"
fluoroforo = "rodamina"
resolucao = "alta"
filtro = 15
lapadaUv = "ligado"
ganho = 0
zoom = 10
campo = "claro"

#Frase de inicializacao do programa 

print("Esse programa tem como objetivo configurar o microscopio confocal de varredura a laser")

#Mensagem para o usuario  
objetiva_desejada = int(input("Informe a objetiva desejada:"))
print("Houve alteração na variável desejada?",objetiva!=objetiva_desejada)
laser_desejado = int(input("Informe o laser desejado:"))
print("Houve alteração na variável desejada?",laser!=laser_desejado)
pinhole_desejado = input("Informe como deseja o pinhole")
print("Houve alteração na variável desejada?",pinhole!=pinhole_desejado)
fluoroforo_desejado = input("Informe o fluoróforo desejado")
print("Houve alteração na variável desejada?",fluoroforo!=fluoroforo_desejado)
resolucao_desejada = input("Informe a qualidade de resolução desejada")
print("Houve alteração na variável desejada?",resolucao!=resolucao_desejada)
filtro_desejado = int(input("Informe o filtro desejado"))
print("Houve alteração na variável desejada?",filtro!=filtro_desejado)
lampadaUv_desejada = input("Informe como deseja a lampada UV")
print("Houve alteração na variável desejada?",lapadaUv!=lampadaUv_desejada)
ganho_desejado = int(input("Informe a quantidade de ganho que deseja utilizar"))
print("Houve alteração na variável desejada?",ganho!=ganho_desejado)
zoom_desejado = int(input("Informe a quantidade de zoom que deseja utilizar"))
print("Houve alteração na variável desejada?",zoom!=zoom_desejado)
campo_desejado = input("informe qual campo deseja utilizar")
print("Houve alteração na variável desejada?",campo!=campo_desejado)

#virgula: separar informações
#!= : diferente
#==: igual
#=: receber
#comparacao de variaveis
print("“As informações de configurações setadas pelo usuário são:")
print("objetivas",objetiva_desejada)
print("laser",laser_desejado)
print("pinhole",pinhole_desejado)
print("fluoroforo",fluoroforo_desejado)
print("resolução",resolucao_desejada)
print("filtro",filtro_desejado)
print("lampadaUv",lampadaUv_desejada)
print("Ganho",ganho_desejado)
print("zoom",zoom_desejado)
print("campo",campo_desejado)

inicial_do_usuario = input("Digite a primeira letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",inicial_do_usuario)
ultima_letra = input("Digite a última letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",ultima_letra)
inicial = input("Digite a primeira letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",inicial)
ultima = input("Digite a última letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",ultima)
print("Houve alguma alteração?",inicial!=inicial_do_usuario)
print("Houve alguma alteração",ultima!=ultima_letra)
inicial = input("Digite a primeira letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",inicial)
ultima = input("Digite a última letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",ultima)
print("Houve alguma alteração?",inicial!=inicial_do_usuario)
print("Houve alguma alteração",ultima!=ultima_letra)
inicial = input("Digite a primeira letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",inicial)
ultima = input("Digite a última letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",ultima)
print("Houve alguma alteração?",inicial!=inicial_do_usuario)
print("Houve alguma alteração",ultima!=ultima_letra)
inicial = input("Digite a primeira letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",inicial)
ultima = input("Digite a última letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",ultima)
print("Houve alguma alteração?",inicial!=inicial_do_usuario)
print("Houve alguma alteração",ultima!=ultima_letra)
inicial = input("Digite a primeira letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",inicial)
ultima = input("Digite a última letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",ultima)
print("Houve alguma alteração?",inicial!=inicial_do_usuario)
print("Houve alguma alteração",ultima!=ultima_letra)
inicial = input("Digite a primeira letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",inicial)
ultima = input("Digite a última letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",ultima)
print("Houve alguma alteração?",inicial!=inicial_do_usuario)
print("Houve alguma alteração",ultima!=ultima_letra)
inicial = input("Digite a primeira letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",inicial)
ultima = input("Digite a última letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",ultima)
print("Houve alguma alteração?",inicial!=inicial_do_usuario)
print("Houve alguma alteração",ultima!=ultima_letra)
inicial = input("Digite a primeira letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",inicial)
ultima = input("Digite a última letra do seu nome para a calibração do equipamento na horizontal")
print("Caracter digitado é:",ultima)
print("Houve alguma alteração?",inicial!=inicial_do_usuario)
print("Houve alguma alteração",ultima!=ultima_letra)

segunda_letra_do_usuario = input("Digite a segunda letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",segunda_letra_do_usuario)
penultima_letra= input("Digite a penúltima letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",penultima_letra)
segunda = input("Digite a segunda letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",segunda)
penultima = input("Digite a penúltima letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",penultima)
print("Houve alguma alteração?",segunda!=segunda_letra_do_usuario)
print("Houve alguma alteração?",penultima!=penultima_letra)
segunda = input("Digite a segunda letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",segunda)
penultima = input("Digite a penúltima letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",penultima)
print("Houve alguma alteração?",segunda!=segunda_letra_do_usuario)
print("Houve alguma alteração?",penultima!=penultima_letra)
segunda = input("Digite a segunda letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",segunda)
penultima = input("Digite a penúltima letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",penultima)
print("Houve alguma alteração?",segunda!=segunda_letra_do_usuario)
print("Houve alguma alteração?",penultima!=penultima_letra)
segunda = input("Digite a segunda letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",segunda)
penultima = input("Digite a penúltima letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",penultima)
print("Houve alguma alteração?",segunda!=segunda_letra_do_usuario)
print("Houve alguma alteração?",penultima!=penultima_letra)
segunda = input("Digite a segunda letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",segunda)
penultima = input("Digite a penúltima letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",penultima)
print("Houve alguma alteração?",segunda!=segunda_letra_do_usuario)
print("Houve alguma alteração?",penultima!=penultima_letra)
segunda = input("Digite a segunda letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",segunda)
penultima = input("Digite a penúltima letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",penultima)
print("Houve alguma alteração?",segunda!=segunda_letra_do_usuario)
print("Houve alguma alteração?",penultima!=penultima_letra)
segunda = input("Digite a segunda letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",segunda)
penultima = input("Digite a penúltima letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",penultima)
print("Houve alguma alteração?",segunda!=segunda_letra_do_usuario)
print("Houve alguma alteração?",penultima!=penultima_letra)
segunda = input("Digite a segunda letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",segunda)
penultima = input("Digite a penúltima letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",penultima)
print("Houve alguma alteração?",segunda!=segunda_letra_do_usuario)
print("Houve alguma alteração?",penultima!=penultima_letra)
segunda = input("Digite a segunda letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",segunda)
penultima = input("Digite a penúltima letra do seu nome para a calibração do equipamento na vertical")
print("Caracter digitado é:",penultima)
print("Houve alguma alteração?",segunda!=segunda_letra_do_usuario)
print("Houve alguma alteração?",penultima!=penultima_letra)

print("A calibração do sistema foi finalizada com sucesso")






